# Generated by Django 3.2.12 on 2022-04-28 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import go3xpress.core.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sender_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sender Name')),
                ('sender_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sender Address')),
                ('sender_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Sender Phone')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sender Email')),
                ('receiver_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Receiver Name')),
                ('receiver_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Receiver Address')),
                ('receiver_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Receiver Phone')),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Receiver Email')),
                ('tracking', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking Number')),
                ('services', models.CharField(blank=True, choices=[('Confidential Doc', 'Documents'), ('International Delivery', 'International Delivery'), ('Pet Shifting', 'Pets Shifting'), ('Fragile Item', 'Fragile Item'), ('Vehicle Deliveries', 'Vehicle Deliveries')], default='International Delivery', max_length=500, null=True, verbose_name='Shipping Services')),
                ('item_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight')),
                ('from_loc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pickup Address')),
                ('to_loc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dropoff Address')),
                ('last_loc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Last Location')),
                ('when_to_deliver', models.DateTimeField(default=go3xpress.core.models.get_date, verbose_name='Delivery Date')),
                ('departure_date', models.DateTimeField(default=go3xpress.core.models.get_date, verbose_name='Departure date')),
                ('delivered_date', models.DateTimeField(default=go3xpress.core.models.get_date, verbose_name='Arrival date')),
                ('delivered', models.BooleanField(default=False)),
                ('held', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_loc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Last Location')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.delivery')),
            ],
        ),
    ]
