# Generated by Django 3.2.12 on 2022-06-03 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='item_name',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Item Name')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.delivery')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
