# Generated by Django 3.2.12 on 2022-06-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220603_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
